modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="funnytools"
version="1.0.0"
displayName="FunnyMod"
displayURL="https://mcreator.net"
credits="Thanks to: MCreator"
authors="Limdis"
description="This Is a FunnyMod"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.funnytools]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.funnytools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration